/* DO NOT EDIT THIS FILE - it is machine generated */
#pragma once
#include <jni.h>



#include <stdio.h>
#include <string.h>
#include "libusb/libusb.h"

#include <stdlib.h>
/* Header for class com_icod_libusb_UsbNative */
#define DEV_MIN		10

#define USB_TIMEOUT	1000	    // 10 secconds
#define DEV_NOT_OPEN	-1
#define WR_ER		-2
#define RD_ER		-3
#define WR_ER_LEN	-21

#define DEBUG

#ifndef _Included_com_icod_libusb_UsbNative
#define _Included_com_icod_libusb_UsbNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_icod_libusb_UsbNative
 * Method:    devFind
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_icod_libusb_UsbNative_devFind
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_icod_libusb_UsbNative
 * Method:    devOpen
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_icod_libusb_UsbNative_devOpen
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_icod_libusb_UsbNative
 * Method:    devWrite
 * Signature: (I[BI)I
 */
 jint  Java_com_icod_libusb_UsbNative_devWrite
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_icod_libusb_UsbNative
 * Method:    devRead
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_icod_libusb_UsbNative_devRead
  (JNIEnv * ,jobject, jint, jbyteArray, jint);

/*
 * Class:     com_icod_libusb_UsbNative
 * Method:    devClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_icod_libusb_UsbNative_devClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_icod_libusb_UsbNative
 * Method:    devIsOpen
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_icod_libusb_UsbNative_devIsOpen
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_icod_libusb_UsbNative
 * Method:    devIsOnline
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_icod_libusb_UsbNative_devIsOnline
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_icod_libusb_UsbNative
 * Method:    dev_setOption
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_icod_libusb_UsbNative_devSetOption
  (JNIEnv *, jobject, jint, jint, jint);

JNIEXPORT jint JNICALL
Java_com_icod_libusb_UsbNative_system(JNIEnv *, jobject , jstring );

JNIEXPORT jbyteArray JNICALL
Java_com_icod_libusb_UsbNative_getProductName(JNIEnv *env, jobject instance, jint dev_no) ;


JNIEXPORT jobject JNICALL
Java_com_icod_libusb_UsbNative_getConnectedDesc(JNIEnv *env, jobject instance, jint dev_no) ;
void throwException(JNIEnv *env, const char *className, const char *mess);
int checkNULL(JNIEnv const *env,const char * log);
#ifdef __cplusplus
}
#endif
#endif
